// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use direct TCP URL for CLI (migrate, db push). prisma+postgres:// proxy breaks migrate dev (P1017).
    url:
      process.env["DIRECT_DATABASE_URL"] ??
      process.env["DATABASE_URL"],
  },
});
